import type { Section } from './types';

export const sequenceContainers: Section = {
    id: 'sequence-containers',
    title: 'Sequence containers',
    structures: [
        {
            name: 'std::vector<T>',
            internals:
                'One contiguous allocation holding size() elements inside a larger capacity(). No gaps between elements.',
            operations: [
                {
                    signature: 'v[i], v.at(i), v.front(), v.back()',
                    best: 'O(1)',
                    average: 'O(1)',
                    amortised: '—',
                    worst: 'O(1)',
                    matters: 'Worst',
                    why: 'Every case is the same. The address is data() + i * sizeof(T), which does not depend on the data or the size.',
                },
                {
                    signature: 'v.push_back(x)',
                    best: 'O(1)',
                    average: 'O(1)',
                    amortised: 'O(1)',
                    worst: 'O(n)',
                    matters: 'Amortised',
                    why: 'Normally it writes into spare capacity. When capacity runs out it allocates a bigger block (1.5x or 2x) and moves all n elements. Geometric growth means that fires once per n cheap pushes, so filling a vector is O(n) in total. The O(n) worst case only matters when one individual call has to be bounded.',
                },
                {
                    signature: 'v.insert(it, x)',
                    best: 'O(1)',
                    average: 'O(n)',
                    amortised: '—',
                    worst: 'O(n)',
                    matters: 'Average',
                    why: 'Elements must stay contiguous, so inserting at index i moves the n - i elements after it. At the end that is 0 moves, at begin() it is n, at a random position n/2. Only insert at the end is reliably cheap.',
                },
                {
                    signature: 'v.erase(it)',
                    best: 'O(1)',
                    average: 'O(n)',
                    amortised: '—',
                    worst: 'O(n)',
                    matters: 'Average',
                    why: 'The same shift in the other direction. Erasing the last element moves nothing; erasing the first moves n - 1.',
                },
                {
                    signature: 'v.pop_back()',
                    best: 'O(1)',
                    average: 'O(1)',
                    amortised: '—',
                    worst: 'O(1)',
                    matters: 'Worst',
                    why: 'Destroy the last element and decrement size. Nothing moves and the allocation is never shrunk, so there is no hidden expensive call.',
                },
                {
                    signature: 'v.reserve(n)',
                    best: 'O(1)',
                    average: 'O(n)',
                    amortised: '—',
                    worst: 'O(n)',
                    matters: 'Worst',
                    why: 'It returns immediately when capacity() is already n, otherwise it allocates once and moves the existing elements. Called once before a fill, that single O(n) removes every reallocation that would follow.',
                },
                {
                    signature: 'std::find(v.begin(), v.end(), x)',
                    best: 'O(1)',
                    average: 'O(n)',
                    amortised: '—',
                    worst: 'O(n)',
                    matters: 'Worst',
                    why: 'There is no index over the values. A hit at the first element is O(1) and a random hit is n/2, but a miss reads all n, and misses are the case to size for.',
                },
            ],
            notes: [
                'Reallocation invalidates all iterators, pointers and references. insert and erase invalidate everything from that position onwards.',
                'The shift is a memmove over contiguous memory, so the constant factor is small.',
                'To drop many elements: v.erase(std::remove(v.begin(), v.end(), x), v.end()), one O(n) pass instead of n erases.',
            ],
        },
        {
            name: 'std::deque<T>',
            internals:
                'An array of pointers to fixed-size blocks. Contiguous within a block, not across blocks.',
            operations: [
                {
                    signature: 'd[i]',
                    best: 'O(1)',
                    average: 'O(1)',
                    amortised: '—',
                    worst: 'O(1)',
                    matters: 'Worst',
                    why: 'Work out which block holds i, then the offset inside it. Two indirections instead of one, but a fixed two.',
                },
                {
                    signature: 'd.push_front(x), d.push_back(x)',
                    best: 'O(1)',
                    average: 'O(1)',
                    amortised: 'O(1)',
                    worst: 'O(n / B)',
                    matters: 'Amortised',
                    why: 'Each end has its own block. When a block fills, a new block is allocated and the pointer array is extended, which copies the n / B block pointers, not the elements. Existing elements never move, which is what vector cannot promise at the front.',
                },
                {
                    signature: 'd.insert(it, x)',
                    best: 'O(1)',
                    average: 'O(n)',
                    amortised: '—',
                    worst: 'O(n)',
                    matters: 'Average',
                    why: 'The same shifting as vector, towards whichever end is nearer, so n/2 rather than n. Still linear.',
                },
            ],
            notes: [
                'push_front and push_back keep references valid but invalidate iterators.',
                'Storage is not one block, so there is no d.data().',
            ],
        },
        {
            name: 'std::list<T> and std::forward_list<T>',
            internals:
                'Each element is a separate heap node holding a pointer to the next node, and for list the previous one too. Nothing is contiguous, so nothing shifts.',
            operations: [
                {
                    signature: 'l.insert(it, x), l.erase(it)',
                    best: 'O(1)',
                    average: 'O(1)',
                    amortised: '—',
                    worst: 'O(1)',
                    matters: 'Worst',
                    why: 'Given the iterator, a fixed number of pointer writes regardless of position or size.',
                },
                {
                    signature: 'reaching the i-th element',
                    best: 'O(1)',
                    average: 'O(n)',
                    amortised: '—',
                    worst: 'O(n)',
                    matters: 'Average',
                    why: 'There is no operator[]. Reaching element i costs i pointer hops, so the O(1) insert above usually sits behind an O(n) walk. Only the two ends are cheap.',
                },
                {
                    signature: 'l.splice(pos, other)',
                    best: 'O(1)',
                    average: 'O(1)',
                    amortised: '—',
                    worst: 'O(1)',
                    matters: 'Worst',
                    why: 'Moving a whole list relinks a few pointers and no element is copied. Splicing a sub-range is O(k) instead, because size() is O(1) and has to be corrected.',
                },
                {
                    signature: 'l.sort()',
                    best: 'O(n log n)',
                    average: 'O(n log n)',
                    amortised: '—',
                    worst: 'O(n log n)',
                    matters: 'Worst',
                    why: 'Merge sort over the links, which does the same work on sorted and unsorted input. It is a member function because std::sort needs random access iterators.',
                },
            ],
            notes: [
                'One allocation and two pointers per element, and traversal jumps around memory, so cache misses dominate.',
            ],
        },
        {
            name: 'std::array<T, N> and std::string',
            internals:
                'array is a fixed-size block with the size known at compile time. string is a vector<char> that keeps short strings inline instead of on the heap.',
            operations: [
                {
                    signature: 'a[i], s[i]',
                    best: 'O(1)',
                    average: 'O(1)',
                    amortised: '—',
                    worst: 'O(1)',
                    matters: 'Worst',
                    why: 'Contiguous, same address arithmetic as vector.',
                },
                {
                    signature: 's += t, s.append(t)',
                    best: 'O(k) for k = len(t)',
                    average: 'O(k)',
                    amortised: 'O(k)',
                    worst: 'O(n + k)',
                    matters: 'Amortised',
                    why: 'Copies t into spare capacity, with the same geometric growth as vector. Appending in a loop is linear in the final length, not quadratic; the O(n + k) case is the reallocation.',
                },
                {
                    signature: 's.substr(pos, len)',
                    best: 'O(1)',
                    average: 'O(len)',
                    amortised: '—',
                    worst: 'O(len)',
                    matters: 'Worst',
                    why: 'It allocates and copies, and the best case is only the empty or short-string one. std::string_view over the same range is O(1), since it holds a pointer and a length.',
                },
                {
                    signature: 's.insert(pos, t), s.erase(pos, len)',
                    best: 'O(1)',
                    average: 'O(n)',
                    amortised: '—',
                    worst: 'O(n)',
                    matters: 'Average',
                    why: 'The tail after pos is shifted, so the cost is n - pos.',
                },
            ],
        },
    ],
};
